# Generated by Django 5.0.4 on 2024-04-27 10:49

import api.utils
import django.core.validators
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Incorrect name string. Names can only contain alphabets, '-' and (space)", regex='^[A-Za-z]+(?:[-\\s]?[A-Za-z]+)*$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Incorrect name string. Names can only contain alphabets, '-' and (space)", regex='^[A-Za-z]+(?:[-\\s]?[A-Za-z]+)*$')])),
                ('dob', models.DateField(validators=[api.utils.validate_date])),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.text.Lower('first_name'), '+', models.Value(' ')), '+', django.db.models.functions.text.Lower('last_name')), name='unique_fullname', violation_error_message='Customer with same first and last names already exists'),
        ),
    ]
